import { Produto } from '../produto'

const produtos: Produto[] = [
    
        {
          id: 1,
          nome: 'Caneca Dia das Mães - "Melhor Mãe do Mundo"',
          descricao: 'Caneca especial para o Dia das Mães, com a frase "Melhor Mãe do Mundo" estampada.',
          imagem: 'https://i.postimg.cc/7ZchWRYd/mothers-day-cup.png',
          nota: 4.9,
          videoRevisao: 'https://www.youtube.com/embed/exampleVideo1',
          tags: ['Dia das Mães', 'Presente'],
          precoBase: 49.99,
          precoPromocional: 39.99,
          menorPreco: 34.99,
          maiorPreco: 59.99,
          precoMedio: 47.99,
          especificacoes: {
              Produto: 'Caneca classe AAA',
              Capacidade: '350 ml',
              Material: 'Cerâmica',
              Altura: '10.00 cm',
              Largura: '8.50 cm',
              Comprimento: '9.50 cm',
              Peso: '330 gr',
              InformaçõesAdicionais: 'Apto para micro-ondas e máquina de lavar louça.',
              destaque: 'Perfeita para presentear sua mãe!'
          },
        },
        {
          id: 2,
          nome: 'Caneca Dia dos Pais - "Pai, o Melhor Super-Herói"',
          descricao: 'Caneca exclusiva para o Dia dos Pais, com a frase "Pai, o Melhor Super-Herói".',
          imagem: 'https://i.postimg.cc/VNz6mhhp/fathers-day-cup.png',
          nota: 4.8,
          videoRevisao: 'https://www.youtube.com/embed/exampleVideo2',
          tags: ['Dia dos Pais', 'Super-Herói', 'Presente'],
          precoBase: 39.99,
          precoPromocional: 29.99,
          menorPreco: 24.99,
          maiorPreco: 49.99,
          precoMedio: 37.99,
          especificacoes: {
              Produto: 'Caneca classe A',
              Capacidade: '330 ml',
              Material: 'Porcelana',
              Altura: '9.50 cm',
              Largura: '8.00 cm',
              Comprimento: '9.50 cm',
              Peso: '320 gr',
              InformaçõesAdicionais: 'Resistente a micro-ondas e lavável em máquinas de lavar louça.',
              destaque: 'Presente criativo para um pai especial!'
          },
        },
        {
          id: 3,
          nome: 'Caneca "Feliz Aniversário"',
          descricao: 'Caneca alegre e colorida, perfeita para comemorar aniversários.',
          imagem: 'https://i.postimg.cc/fb0pG7GC/MOCKUPS-DIA-DAS-M-ES-1-050-removebg-preview.png',
          nota: 4.7,
          videoRevisao: 'https://www.youtube.com/embed/exampleVideo3',
          tags: ['Aniversário', 'Festa'],
          precoBase: 44.99,
          precoPromocional: 34.99,
          menorPreco: 29.99,
          maiorPreco: 54.99,
          precoMedio: 39.99,
          especificacoes: {
              Produto: 'Caneca classe AAA',
              Capacidade: '300 ml',
              Material: 'Porcelana',
              Altura: '9.00 cm',
              Largura: '8.00 cm',
              Comprimento: '9.00 cm',
              Peso: '310 gr',
              InformaçõesAdicionais: 'Adequada para micro-ondas e lavável na máquina de lavar louça.',
              destaque: 'A caneca ideal para festas de aniversário!'
          },
        },
        {
          id: 4,
          nome: 'Caneca Dia dos Namorados - "Te Amo"',
          descricao: 'Caneca romântica para o Dia dos Namorados, com a frase "Te Amo".',
          imagem: 'https://i.postimg.cc/K8t7F9vX/valentines-day-mug.png',
          nota: 5.0,
          videoRevisao: 'https://www.youtube.com/embed/exampleVideo4',
          tags: ['Dia dos Namorados', 'Romântica', 'Presente'],
          precoBase: 54.99,
          precoPromocional: 44.99,
          menorPreco: 39.99,
          maiorPreco: 69.99,
          precoMedio: 52.99,
          especificacoes: {
              Produto: 'Caneca classe AAA',
              Capacidade: '350 ml',
              Material: 'Cerâmica',
              Altura: '9.50 cm',
              Largura: '8.50 cm',
              Comprimento: '9.50 cm',
              Peso: '340 gr',
              InformaçõesAdicionais: 'Pode ser usada em micro-ondas e lavada em máquina de lavar louça.',
              destaque: 'Surpreenda seu amor com um presente único!'
          },
        },
        {
          id: 5,
          nome: 'Caneca "Primeiro Café do Dia"',
          descricao: 'Caneca divertida e prática para os amantes de café, com a frase "Primeiro Café do Dia".',
          imagem: 'https://i.postimg.cc/BQppVn6s/coffee-mug.png',
          nota: 4.6,
          videoRevisao: 'https://www.youtube.com/embed/exampleVideo5',
          tags: ['Café', 'Manhã', 'Café da Manhã'],
          precoBase: 29.99,
          precoPromocional: 24.99,
          menorPreco: 19.99,
          maiorPreco: 39.99,
          precoMedio: 27.99,
          especificacoes: {
              Produto: 'Caneca classe A',
              Capacidade: '300 ml',
              Material: 'Porcelana',
              Altura: '9.00 cm',
              Largura: '8.50 cm',
              Comprimento: '8.50 cm',
              Peso: '290 gr',
              InformaçõesAdicionais: 'Ideal para café e outras bebidas quentes.',
              destaque: 'A escolha perfeita para começar o dia com café!'
          },
        },
        {
          id: 6,
          nome: 'Caneca "Melhor Amiga"',
          descricao: 'Caneca perfeita para presentear aquela amiga especial.',
          imagem: 'https://i.postimg.cc/C5HF5Ln6/best-friend-cup.png',
          nota: 4.8,
          videoRevisao: 'https://www.youtube.com/embed/exampleVideo6',
          tags: ['Amiga', 'Presente'],
          precoBase: 39.99,
          precoPromocional: 29.99,
          menorPreco: 24.99,
          maiorPreco: 49.99,
          precoMedio: 37.99,
          especificacoes: {
              Produto: 'Caneca classe AAA',
              Capacidade: '320 ml',
              Material: 'Porcelana',
              Altura: '9.50 cm',
              Largura: '8.00 cm',
              Comprimento: '9.00 cm',
              Peso: '310 gr',
              InformaçõesAdicionais: 'Lavável em máquina de lavar louça e resistente a micro-ondas.',
              destaque: 'Uma linda opção de presente para sua melhor amiga!'
          },
        },
        {
          id: 7,
          nome: 'Caneca "Super Professora"',
          descricao: 'Caneca para homenagear as professoras, com a frase "Super Professora".',
          imagem: 'https://i.postimg.cc/7LFV5BhG/super-teacher-mug.png',
          nota: 4.9,
          videoRevisao: 'https://www.youtube.com/embed/exampleVideo7',
          tags: ['Professora', 'Homenagem'],
          precoBase: 42.99,
          precoPromocional: 34.99,
          menorPreco: 29.99,
          maiorPreco: 49.99,
          precoMedio: 40.99,
          especificacoes: {
              Produto: 'Caneca classe AAA',
              Capacidade: '350 ml',
              Material: 'Cerâmica',
              Altura: '9.50 cm',
              Largura: '8.50 cm',
              Comprimento: '9.50 cm',
              Peso: '340 gr',
              InformaçõesAdicionais: 'Pode ser usada no micro-ondas e lavada na máquina de lavar louça.',
              destaque: 'Para homenagear aquela professora especial!'
          },
        },
        {
          id: 8,
          nome: 'Caneca "Café e Amor"',
          descricao: 'Caneca charmosa com a frase "Café e Amor", ideal para os apaixonados por café.',
          imagem: 'https://i.postimg.cc/FFqzZGmb/coffee-and-love.png',
          nota: 4.7,
          videoRevisao: 'https://www.youtube.com/embed/exampleVideo8',
          tags: ['Café', 'Romance'],
          precoBase: 34.99,
          precoPromocional: 24.99,
          menorPreco: 19.99,
          maiorPreco: 39.99,
          precoMedio: 32.99,
          especificacoes: {
              Produto: 'Caneca classe A',
              Capacidade: '300 ml',
              Material: 'Porcelana',
              Altura: '9.00 cm',
              Largura: '8.50 cm',
              Comprimento: '8.50 cm',
              Peso: '290 gr',
              InformaçõesAdicionais: 'Apto para micro-ondas e lavável na máquina de lavar louça.',
              destaque: 'Caneca romântica para os momentos de café!'
          },
        },
        {
          id: 9,
          nome: 'Caneca "Eu Amo Café"',
          descricao: 'Caneca divertida e moderna, com a frase "Eu Amo Café".',
          imagem: 'https://i.postimg.cc/TY7HknXz/love-coffee-mug.png',
          nota: 4.5,
          videoRevisao: 'https://www.youtube.com/embed/exampleVideo9',
          tags: ['Café', 'Amor'],
          precoBase: 26.99,
          precoPromocional: 19.99,
          menorPreco: 15.99,
          maiorPreco: 35.99,
          precoMedio: 25.99,
          especificacoes: {
              Produto: 'Caneca classe A',
              Capacidade: '350 ml',
              Material: 'Cerâmica',
              Altura: '9.00 cm',
              Largura: '8.00 cm',
              Comprimento: '9.50 cm',
              Peso: '300 gr',
              InformaçõesAdicionais: 'Resistente a micro-ondas e lavável em máquina de lavar louça.',
              destaque: 'A caneca ideal para os amantes de café!'
          },
        },
        {
          id: 10,
          nome: 'Caneca "Eu Sou Foda"',
          descricao: 'Caneca com a frase motivacional "Eu Sou Foda", perfeita para se lembrar da sua força.',
          imagem: 'https://i.postimg.cc/6pQXvvDW/motivational-mug.png',
          nota: 4.6,
          videoRevisao: 'https://www.youtube.com/embed/exampleVideo10',
          tags: ['Motivação', 'Autoconfiança'],
          precoBase: 32.99,
          precoPromocional: 24.99,
          menorPreco: 21.99,
          maiorPreco: 39.99,
          precoMedio: 30.99,
          especificacoes: {
              Produto: 'Caneca classe A',
              Capacidade: '300 ml',
              Material: 'Porcelana',
              Altura: '9.00 cm',
              Largura: '8.50 cm',
              Comprimento: '9.00 cm',
              Peso: '310 gr',
              InformaçõesAdicionais: 'Adequada para micro-ondas e máquina de lavar louça.',
              destaque: 'Para momentos de autoconfiança!'
          },
        },
      ]
      
export default produtos
