# Usar a imagem oficial do PostgreSQL
FROM postgres:latest

# Definir variáveis de ambiente para o PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=postgres

# Expor a porta padrão do PostgreSQL
EXPOSE 5432
