GET http://localhost:4000/pedidos

###
GET http://localhost:4000/pedidos/1

###
DELETE http://localhost:4000/pedidos/1

###
POST http://localhost:4000/pedidos
Content-Type: application/json

{
    "usuarioId": "55c605af-f763-4f31-b7e1-f75405581124",
    "data": "2021-09-01T00:00:00.000Z",
    "valorTotal": 200.00,
    "status": "PENDENTE",
    "formaPagamento": "CARTAO",
    "entrega": {
        "nome": "Fulano",
        "email": "fulano@email.com",
        "cpf": "123.456.789-00",
        "logradouro": "Rua dos Bobos, 0",
        "complemento": "Apto 101",
        "cidade": "São Paulo",
        "estado": "SP"
    },
    "itens": [
        {
            "quantidade": 1,
            "precoUnitario": 100.00,
            "produtoId": 11
        },
        {
            "produtoId": 2,
            "precoUnitario": 100.00,
            "quantidade": 11
        }
    ]
}
